spring:
  security:
    user:
      password: 2ce1414d-e44c-48f7-9286-a76eaa7c53e2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: 'false'
  redis:
    port: 6379
    host: j8c206.p.ssafy.io
    password: ssafy
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
    open-in-view: true
    database: mysql
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      password: nVNUcEiOY5
#      username: S08P23C206@stg-yswa-kr-practice-db-master
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/s08p23c206

#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tlens?serverTimezone=Asia/Seoul
#    username: root
#    password: ssafy

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ssafy
      username: root
    url: jdbc:mysql://j8c206.p.ssafy.io:3306/tlens
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

jwt:
  accessTokenExpiration: '18000000000' #'1800000'
  refreshTokenExpiration: '604800000'
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

springdoc:
  packages-to-scan: com.ssafy.tlens # swagger를 적용하기 위해 스캔할 패키지를 지정합니다.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

server:
  servlet:
    encoding:
      enabled: 'true'
      force: 'true'
      charset: UTF-8
    context-path: /api/v1
  port: 8080
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spa:
  default-file: /dist/index.html

file:
  path: /usr/local/share
  path-certificate: /usr/local/share


common-code:
  evaluation-question-parent-id: 1
  category-parent-id: 2
